name: Greetings

on:
  pull_request:
    branches: [ main ]
  issues:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      myTestInp:
        description: "Test description"
        default: "this is the deafult value"
        required: true
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users first issue'
        pr-message: 'Message that will be displayed on users first pull request'
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: print name
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
          echo ${{secrets.TEST_SEC}}
